### ISSUE TITLE
How can Item=Point image be changed to Diamond?

### ISSUE THREAD

**Issue by gwinterhalter** [visjs/vis-timeline#130]
HI All;

Can anyone provide example how to change Item=Point to a diamond? Thanks all.

Greg

**Comment by yotamberk** [comment]
Add this:
``` css
.vis-point .vis-item.vis-dot {
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-bottom-color: #97b0f8;
      top: 3px!important;
      background-color: transparent;
      border-radius: 0;
      
    }
    .vis-point .vis-item.vis-dot:after {
      content: '';
      position: absolute;
      left: -5px;
      top: 5px;
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-top-color: #97b0f8;
    }
```

**Comment by yotamberk** [comment]
Add this:
``` css
.vis-point .vis-item.vis-dot {
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-bottom-color: #97b0f8;
      top: 3px!important;
      background-color: transparent;
      border-radius: 0;
      
    }
    .vis-point .vis-item.vis-dot:after {
      content: '';
      position: absolute;
      left: -5px;
      top: 5px;
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-top-color: #97b0f8;
    }
```
