### ISSUE TITLE
The 'Point' is not on the exact datetime if data type : 'point'

### ISSUE THREAD

**Issue by kmku** [visjs/vis-timeline#450]
Say, refereing to this example:
https://visjs.github.io/vis-timeline/examples/timeline/editing/editingItems.html

Item 5 is on 2014-01-28 
{id: 5, content: 'item 5', start: '2014-01-28', type:'point'},
but, it is shifted to the right.

**Comment by yotamberk** [comment]
It seems to be due to local time vs utc time.

**Comment by bricksphd** [comment]
Here's a CodePen showing the same point offset problem:
https://codepen.io/bricksphd/pen/LYZmLaO

**Comment by knokit** [comment]
I encountered the same issue. I'm displaying the times in UTC (https://visjs.github.io/vis-timeline/docs/timeline/#Time_zone) and it also renders the point items with an offset.

It's been a year since this bug was reported, is there any plan to fix it or a temporary workaround?

**Comment by knokit** [comment]
For anybody looking for a quick workaround, you can solve this by adjusting the css:

```css
vis-item.vis-point > .vis-dot {
    transform: translateX(-4px) !important;
}

.vis-item.vis-point > .vis-item-content {
    margin-left: 4px !important;
}
```
