### ISSUE TITLE
Give the pop-up tooltip a class so it is styleable

### ISSUE THREAD

**Issue by UnicornDeluxe** [visjs/vis-timeline#8]
Hey,
this request was originally raised [here](https://github.com/almende/vis/issues/626) but seems [not to work](http://jsfiddle.net/hpb06ac5/) with the timeline.
Would be really nice if this could be implemented for the timeline as well.

**Comment by mojoaxel** [comment]
This should not be hard to implement.
I think we should wait for the upcoming v6 release and than see how to approach this.

**Comment by yotamberk** [comment]
Try adding this instead:
``` css
.vis-tooltip {
  background-color: red!important;
  color: white!important;
}
```
